### ISSUE TITLE
Does it matter if the frame batches < 10?

### ISSUE THREAD

**Issue by yzheng97** [LuoweiZhou/ProcNets-YouCook2#1]
The length of my own data varies.

> local aug_frame_shift = math.max(math.floor(sampling_itv/10),1)*frames_per_video/total_frame -- 10 is temporal aug factor, hard coded

It seems that the batch number must be set to a const number ?

**Comment by LuoweiZhou** [comment]
Yes, for now, the batch_size is always 1, as indicated [here](https://github.com/LuoweiZhou/ProcNets-YouCook2/blob/587bd97135b153a31c2978f273e6de12a852e0fd/train_bilstm_seq.lua#L88)

**Comment by yzheng97** [comment]
Thanks!
