### ISSUE TITLE
Where can I download annotation of testing set?

### ISSUE THREAD

**Issue by friskit-china** [LuoweiZhou/ProcNets-YouCook2#3]
Hi,

Thanks for your code that achieves a promising result.

But you only provided the download link of Train+Val on the website (http://youcook2.eecs.umich.edu/).
Can I get the labels of testing dataset?

**Comment by LuoweiZhou** [comment]
Hi,

Thanks for your interest. We will be hosting the evaluation server on CodaLab soon, for this work and our follow-up work on dense video captioning (http://openaccess.thecvf.com/content_cvpr_2018/CameraReady/0037.pdf). Will keep you informed here. Please stay tuned!

Best,
Luowei

**Comment by LuoweiZhou** [comment]
The leaderboard for YouCook2 test set is available here: http://youcook2.eecs.umich.edu/leaderboard

**Comment by friskit-china** [comment]
Hi,

Do you have a plan to release all the raw videos?
I tried to download all these videos by youtube-dl, but there are about 100 videos have been removed from YouTube. Is there any possible way to get these unavailable videos or entire 2000 videos introduced in your dataset?

Thanks!

**Comment by LuoweiZhou** [comment]
I've CC'd Nathan who can help you with this. Could you send him a list of
missing videos? Thank you both.

**Comment by friskit-china** [comment]
Thanks!

There are 95 videos cannot be downloaded anymore, the following is the youtube ids of these videos, and how can I get in touch with Nathan? by email or in this issue thread?

6hs8dZuzIFs
ekguuiYx5xU
GyLX64aJY80
nJ6fxiFKHaE
mtX4PAsQR70
BjWYw7V_T0s
8Wx28xP3R70
2QtUtQMVoG8
QTSklobANsU
e-GfjjZMabA
1uCNsybhEAg
3bUVlO-kmhw
HghNzA9BJAU
MZbrWzqEntk
_T6wD5toQF8
jJDFCCaLRIE
524UzHtbAcY
wch6oe0FjN8
nRojh0N1QiU
2Ymt5frHtTg
Os-sHx3zM4Q
txjgF4URKDw
pvGBm2epEo0
2Zr72r4OCe8
zXYs_tPYAvc
WCBuVWAvJYE
Wi9BWzwPsfA
byBVHb9z8Kc
t5ookHohDFc
PXYabjc__UU
ZIgpIiXxbJw
jivDSCDoyU0
qSGeNRE8DIA
1IE3Z0wBnLU
mCc1T7zOKjA
RubyHelAHBE
1BYKKEvxcVo
r7i0dgOLdoo
k38Al8giI-U
lYIdHAgj64Y
Xf-2YtP05Bs
57e54HEcrUE
sGZQ8haMF8s
t1cUwX4Xzt0
ysmNrW8Yg58
4e4T8xaQsw0
rpNzQZqj0JQ
mrHTodOjHOc
9gCDpktlxfs
lpWOv7Y3JHM
dqksjDlrqq8
sJVn7H0pQRw
pDrk2MNTepY
2rYhzpo4bY0
_gG0As2y92g
ItEqiHzbLj4
vU2lND4YQjM
5cqJkRqbHrs
r4MPTWizETs
UbRRHp4uO50
DeiX_otgD1Q
mKDT_D1-Ym4
fIRadWyEofw
bUQ_OAQNyj8
HwLNy9MV6AQ
PSXBOFO-NHs
0-OWf7eul6w
19EkHqTQkZg
YA6lhxwLrUI
9Y9_OBnJub0
TkK7BbBNPaY
x6noOknBPDI
RXljYbddo7g
fokJxFjWJfs
cQ8VpMhqzZ0
MJ2mD3blxqA
f2uDKzq8WM0
UesiELtgiVk
1vJp-jaIaeE
8Z9iWc70sFc
4AIahLZfNq4
zaJrdbEGBj0
8SVzabm5e3Q
A6icBIwaT8c
GtVEasGxGpM
W2gnFLOi_AQ
30Q8k57Kbz4
838pWl1iNKk
oC5OvA4BK-E
BAoQWVV-bh4
kXoSzxkZsx8
aqH_V3yLtrY
yreC9D4yYiM
zgfwA7qt0lg
4h33GFHLPNg

**Comment by LuoweiZhou** [comment]
@friskit-china please email Nathan (natlouis@umich.edu) your *missing_videos.txt* generated by our script. Thank you.
