### ISSUE TITLE
WARNING: The url doesn't specify the protocol, trying with http

### ISSUE THREAD

**Issue by zjmlovlin** [LuoweiZhou/ProcNets-YouCook2#4]
/usr/bin/python2.7 /home/zhangjianming/data/youcook/YouCookII/scripts/download_youcookii_videos.py
WARNING: The url doesn't specify the protocol, trying with http
[youtube] Ysh60eirChU: Downloading webpage
[youtube] Ysh60eirChU: Downloading video info webpage

what is the problem?

**Comment by natlouis** [comment]
It seems to be just a warning and the videos still download. But the warning goes away when adding `http://` or `https://` to line 29 in download_youcookii_videos.py.
