### ISSUE TITLE
Unable to download webpage

### ISSUE THREAD

**Issue by zjmlovlin** [LuoweiZhou/ProcNets-YouCook2#5]
when I try to down the youcook2.I have a problem,and I have added http or https.
I don't know if it is because I am  in China.
/usr/bin/python2.7 /home/zhangjianming/data/youcook/YouCookII/scripts/download_youcookii_videos.py
[youtube] Ysh60eirChU: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLError(error(110, 'Connection timed out'),))
[INFO] Cannot download training video Ysh60eirChU
[youtube] jpQBWsR3HHs: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))
[INFO] Cannot download training video jpQBWsR3HHs
[youtube] QWXlKD-XGCQ: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))
[INFO] Cannot download training video QWXlKD-XGCQ
[youtube] 5E3kulJRzGY: Downloading webpage

**Comment by zjmlovlin** [comment]
I try one of the url
youtube-dl --verbose https://www.youtube.com/watch?v=Ysh60eirChU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=Ysh60eirChU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[youtube] Ysh60eirChU: Downloading webpage
[youtube] Ysh60eirChU: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r3---sn-i3b7knlk.googlevideo.com/videoplayback?c=WEB&ei=-ldEXKHXFoni4QKT7oSgBA&source=youtube&pl=32&gir=yes&initcwndbps=843750&expire=1548004442&mt=1547982765&mv=m&clen=110674404&ms=au%2Conr&mm=31%2C26&mn=sn-i3b7knlk%2Csn-un57en7l&keepalive=yes&ipbits=0&requiressl=yes&itag=136&id=o-AOQDCGD-x2iFt5jHnntkzdmvwYWGeDvJ1NC-JCcoNEi0&lmt=1390188565808921&dur=609.920&ip=2001%3Ada8%3A7001%3A119%3A92f%3A76fb%3Ab3ac%3A5f93&key=yt6&signature=708BEF13F42A3041DDDC2D6FF1B7A1DC4F72543C.1BDA878F58F50DD732BC2C5750D099397A15EA63&aitags=133%2C134%2C135%2C136%2C160&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&fvip=3&mime=video%2Fmp4&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1140, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by LuoweiZhou** [comment]
@zjmlovlin sorry for the delay. Have you managed to download the videos? Some videos might not be available in your region. Please send me (luozhou@umich.edu) an email I can share the missing videos with you.

**Comment by weiwuxian1998** [comment]
Hi，I also try to download raw videos of youcookii, but even I used a VPN, the download speed was quite slow, for exmple, 35~60k/s. It would be kind if you can provide a google drive or baidu cloud link for China mainland researchers, Thanks again.

**Comment by myccver** [comment]
> Hi，I also try to download raw videos of youcookii, but even I used a VPN, the download speed was quite slow, for exmple, 35~60k/s. It would be kind if you can provide a google drive or baidu cloud link for China mainland researchers, Thanks again.

您好，有些视频似乎损坏了无法播放。请问您后来获取了完整的原视频了吗？

**Comment by yangxingrui** [comment]
现在，我也遇到了相同的问题，下载YouTube原始视频时，遇到Youtuber删除账号、视频转为私有、视频无法再播放等一系列问题，如果您能提供给我完整的原始视频，我将不胜感激！

**Comment by myccver** [comment]
> 现在，我也遇到了相同的问题，下载YouTube原始视频时，遇到Youtuber删除账号、视频转为私有、视频无法再播放等一系列问题，如果您能提供给我完整的原始视频，我将不胜感激！

您好，请问您收集到了这个数据集的原视频了吗？

**Comment by yhd-123** [comment]
Could you provide a google drive to share all videos with me? thanks a lot!

**Comment by yhd-123** [comment]
Could you provide a google drive to share all videos with me at a1345467505@gmail.com? thanks a lot!

**Comment by yangxingrui** [comment]
> > 现在，我也遇到了相同的问题，下载YouTube原始视频时，遇到Youtuber删除账号、视频转为私有、视频无法再播放等一系列问题，如果您能提供给我完整的原始视频，我将不胜感激！
> 
> 您好，请问您收集到了这个数据集的原视频了吗？

是的，如果你因为进行VLTint的后续工作需要YouCook2原视频，那么可以通过email联络natlouis@umich.edu获取到YouTube原视频，请注意：请先自己从YouTube下载视频，并将意外无法下载的视频保存为missing_videos.txt，将missing_videos.txt同时发送给natlouis@umich.edu，他会热心帮助你。同时注意到，luozhou@umich.edu也来自umich，应该也可以帮助到你，以上。另，祝你圣诞快乐！

**Comment by vhzy** [comment]
> 现在，我也遇到了相同的问题，下载YouTube原始视频时，遇到Youtuber删除账号、视频转为私有、视频无法再播放等一系列问题，如果您能提供给我完整的原始视频，我将不胜感激！

您好，请问您收到数据集了吗，我也遇到同样问题，如能分享视频数据集，不胜感激！
email:chinabbhzy@gmail.com or 1051777434@qq.com

**Comment by harrytea** [comment]
> Have you solved the problem? Could you provide a google drive or baidu drive to share all videos with me at wangyh1206@gmail.com? thanks a lot!

**Comment by natlouis** [comment]
We have now made all raw video files available for download for non-commercial, research purposes only. They can be found on the YouCook2 [Downloads](http://youcook2.eecs.umich.edu/download) page.
