### ISSUE TITLE
What is the ResNet's input size?

### ISSUE THREAD

**Issue by v-iashin** [LuoweiZhou/ProcNets-YouCook2#6]
Thanks for sharing the code for your paper. I am wondering what is the input size for the ResNet that you use for feature extraction? Is it 224 x 224 or something else?

**Comment by LuoweiZhou** [comment]
Yes, 224x224
https://github.com/LuoweiZhou/ProcNets-YouCook2/blob/380f54752f43405f6760c1aa328608a5b0503251/extract_resnet_feat.lua#L101

**Comment by v-iashin** [comment]
Thanks. I saw this exact line, but I am not familiar with Lua, so I wanted to check my guess.
